services:
    builder:
        environment:
            BUILDER_CONFIGURE: "--enable-packetver=20200401"

    web:
        image: "rathena:local"
        container_name: "rathena-web"
        command: sh -c "/bin/wait-for db:3306 -- /rathena/web-server"
        ports:
            - "8888:8888"
        volumes:
            - "../..:/rathena"
            - "./asset/inter_conf.txt:/rathena/conf/import/inter_conf.txt"
        init: true
        tty: true
        stdin_open: true
        depends_on:
            - char
